# 开发相关别名

alias npmi='npm install'
alias npmg='npm install -g'
alias npmr='npm run'
alias npmt='npm test'
alias npmb='npm run build'
alias npml='npm run lint'
alias npmd='npm run dev'
alias yarni='yarn install'
alias yarna='yarn add'
alias yarnad='yarn add -D'
alias yarnr='yarn run'

alias pnpi='pnpm install'
alias pnpmr='pnpm run'
alias pip='pip3.13'
alias pipi='pip3 install'
alias pipu='pip3 install --upgrade'
alias pipr='pip3 install -r requirements.txt'
alias pipf='pip3 freeze'
alias venv='python3 -m venv'
alias serve='python3 -m http.server'
alias json='python3 -m json.tool'
alias yamllint='yamllint'