# 网络相关别名
alias ping='ping -c 5'
alias fastping='ping -c 1 -s 1'
alias ports='netstat -tulanp'
alias netstat='netstat -an | grep'
alias listen='lsof -iTCP -sTCP:LISTEN -nP'
alias myip='curl ifconfig.me'
alias localip='ipconfig getifaddr en0'
alias ipinfo='curl ipinfo.io'
alias dnsflush='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
alias traceroute='traceroute -q 1'
alias nmap='nmap -sS -O'
alias whois='whois -H'
alias http='python3 -m http.server'
alias https='python3 -m http.server --bind 0.0.0.0 443'