# 系统相关别名
alias df='df -h'
alias du='du -h'
alias duh='du -h --max-depth=1'
alias free='free -h'
# alias top='htop'
alias psmem='ps aux | sort -nr -k 4'
alias pscpu='ps aux | sort -nr -k 3'
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'
alias histg='history | grep'
alias now='date +"%T"'
alias nowdate='date +"%Y-%m-%d"'
alias weather='curl wttr.in'
alias mkdir='mkdir -pv'
alias wget='wget -c'
alias hist='history'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias path='echo -e ${PATH//:/\\n}'
alias nowtime='date +"%T"'